---
- name: Compare filters results with j2 variables from inventory
  include_tasks: tests.yml
  when: check_filters is defined and check_filters

- name: Define j2 variables from inventory
  set_fact:
    j2_icebergs_groups_list: "{{ groups | icebergs_groups_list(iceberg_naming) }}"
    j2_number_of_icebergs: "{{ groups | number_of_icebergs(iceberg_naming) }}"
    j2_current_iceberg: "{{ hostvars[inventory_hostname] | current_iceberg }}"
    j2_current_iceberg_number: "{{ hostvars[inventory_hostname] | current_iceberg_number }}"
    j2_current_iceberg_network: "{{ hostvars[inventory_hostname] | current_iceberg_network }}"
    j2_equipment_groups_list: "{{ groups | equipment_groups_list(equipment_naming) }}"
    j2_master_groups_list: "{{ groups | master_groups_list(master_groups_naming) }}"
    j2_node_main_network: "{{ hostvars[inventory_hostname] | node_main_network }}"
    j2_node_main_network_interface: "{{ hostvars[inventory_hostname] | node_main_network_interface }}"
